# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-28 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='图标'),
        ),
    ]
